### ISSUE TITLE
LogInit: Error: FLinuxApplication::CreateLinuxApplication() : InitSDL() failed, cannot create application instance.

### ISSUE THREAD

**Issue by slnh312** [adamrehn/pixel-streaming-linux#4] opened 2020-03-10 11:45 UTC
Hi，adam，I'm sorry to bother you again.I have tried your suggestion and I run the sample project: https://github.com/adamrehn/ue4-sample-project ,but it happens as follow,
[2020.03.10-11.25.06:271][  0]LogInit: Warning: Could not initialize SDL: XRandR support is required but not available
[2020.03.10-11.25.06:271][  0]LogInit: Error: FLinuxApplication::CreateLinuxApplication() : InitSDL() failed, cannot create application instance.

![error](https://user-images.githubusercontent.com/52794487/76309353-98efe180-6307-11ea-93da-c238aa4f7e5a.PNG)

**Comment by adamrehn** [comment] 2020-03-11 06:06
As stated by the error message, you need XRandR support installed. Make sure you have the relevant packages installed for your Linux distribution (e.g. for Ubuntu this would be [libxrandr2](https://packages.ubuntu.com/bionic/libxrandr2) and [x11-xserver-utils](https://packages.ubuntu.com/bionic/x11-xserver-utils).)

**Comment by slnh312** [comment] 2020-03-11 08:06
thks a lot , but I still cannot start the PixelStreaming plug-in as you did in the video of “Pixel Streaming in Linux containers”. What should I do? I cannot find the executable files in Linux in the corresponding directory. All the files are similar to the .bat or .exe files in Windows.
![image](https://user-images.githubusercontent.com/52794487/76395459-4f100580-63b2-11ea-986a-7d8a3714ad0e.png)

what's more,I ran the command you recommended me for ue4-sample - project and the result was as follows, as if it was stuck?
![kasi](https://user-images.githubusercontent.com/52794487/76403252-99e44a00-63bf-11ea-9d81-279fc5428a1d.PNG)

**Comment by adamrehn** [comment] 2020-03-11 11:29
Oops, it looks like I forgot to add the `WebRTCProxy` target to the list that gets built when creating an Installed Build of the Engine. I've added that now in [commit f713064](https://github.com/adamrehn/UnrealEngine/commit/f713064cf5fd216faec3ad4bd1e5b7baef5c192a), so in theory you should just need to rebuild the container image and the required files should be there. I'll perform a rebuild myself tomorrow to confirm that this is the case.

**Comment by slnh312** [comment] 2020-03-12 01:34
Don't SignalingWebServers need to be added to the list?

**Comment by slnh312** [comment] 2020-03-12 03:43
I hava built the latest version including the commit f713064 under Ubuntu18.04，not in docker，but could not find any distinctions with before。
![image](https://user-images.githubusercontent.com/52794487/76485157-a5368480-6456-11ea-9898-784230d9b447.png)

**Comment by slnh312** [comment] 2020-03-12 05:44
I used the latest version to rebuild, but an error was reported:

![fail](https://user-images.githubusercontent.com/52794487/76491014-8f7d8b00-6467-11ea-83aa-9a3f17642c4b.PNG)

**Comment by adamrehn** [comment] 2020-03-12 06:16
The signalling and matchmaking webservers are already present under `Engine/Source/Programs/PixelStreaming/WebServers`, so no modifications are required in order to include them.

That's very strange, for some reason my modifications to `WebRTC.Build.cs` weren't included in my initial commit, which is what's causing that error. I've re-added the changes in [commit 7907a0e](https://github.com/adamrehn/UnrealEngine/commit/7907a0e57779845f0c38a1ee7e378a00a5d0701c) and double checked to make sure that nothing else is missing, so hopefully everything should build nicely now. I've restarted my build, so I'll have confirmation of that in a little while.

**Comment by slnh312** [comment] 2020-03-12 08:28
I rebuilt on Ubuntu 18.04（not in container）, referring to the official build guide（https://wiki.unrealengine.com/Building_On_Linux）. After the build, I did not find any difference than before. The files in the /UnrealEngine/Engine/Source/Programs/PixelStreaming/WebRTCProxy/bin directory are the same as those before the build, and there is no executable file of the Linux version.

![build](https://user-images.githubusercontent.com/52794487/76502187-8f3cba00-647e-11ea-8a0f-71e75acaa9dc.PNG)

**Comment by adamrehn** [comment] 2020-03-12 08:40
My own rebuild of the container images based on the latest commit has now completed, and I can confirm that the `WebRTCProxy` binary is indeed present:

```bash
ue4@2a6b15db6c23:~/UnrealEngine/Engine/Source/Programs/PixelStreaming/WebRTCProxy/bin$ ls -lsa
total 78428
    4 drwxr-xr-x 2 ue4 ue4     4096 Mar 12 07:55 .
    4 drwxr-xr-x 3 ue4 ue4     4096 Mar 12 07:55 ..
15064 -rwxr-xr-x 1 ue4 ue4 15421896 Mar 12 07:34 WebRTCProxy
57600 -rw-r--r-- 1 ue4 ue4 58978632 Mar 12 07:34 WebRTCProxy.debug
 5756 -rw-r--r-- 1 ue4 ue4  5890051 Mar 12 07:34 WebRTCProxy.sym
```

**Comment by slnh312** [comment] 2020-03-12 09:01
Thank you. Is the build result in Docker different from that in Linux host? What are the differences in the build processes in the two environments? my rebuild of the container is running，I will check it after the build is over.

**Comment by adamrehn** [comment] 2020-03-12 09:05
The build results should be exactly the same on the host system as they are in a container, so long as you run the same [command to create the Installed Build of the Engine](https://github.com/adamrehn/ue4-docker/blob/v0.0.58/ue4docker/dockerfiles/ue4-minimal/linux/Dockerfile#L29).

**Comment by slnh312** [comment] 2020-03-13 09:14
I built an image today using the latest version, and it doesn't work properly in the container. The attachment is the error log. Please help me to find out which part is the problem.following is my command in a container:
`ue4@732300dcf4d0:~/UnrealEngine/Engine/Binaries/Linux$ DISPLAY='' ./UE4Editor -opengl4 -nosplash`

following is  the log:
[UE4_running1.log](https://github.com/adamrehn/pixel-streaming-linux/files/4328709/UE4_running1.log)

**Comment by adamrehn** [comment] 2020-03-13 09:30
I can't see any mention of your GPU or its OpenGL feature support in that output, which suggests that you're attempting to run the Editor inside a container without [GPU acceleration enabled using the NVIDIA Container Toolkit](https://unrealcontainers.com/docs/concepts/nvidia-docker). If so, crashing on RHI initialisation is the expected behaviour.

**Comment by slnh312** [comment] 2020-03-13 11:23
I am very sorry that I have missed the ue4-runtime build process,now rebuild it including the ue4-runtime,but a new error happens:
![image](https://user-images.githubusercontent.com/52794487/76616892-026a2d00-6560-11ea-82c2-6e42ecdcdc25.png)

**Comment by adamrehn** [comment] 2020-03-13 12:46
I'd suggest taking a look at the [Cloud Rendering](https://unrealcontainers.com/docs/use-cases/cloud-rendering) page of the Unreal Containers documentation, since I suspect that you're not running the container with the correct parameters to enable GPU acceleration.

**Comment by slnh312** [comment] 2020-03-16 06:35
Hi，Adam，I have rebuilt the UE4 project，and I ran a container with the new image，it shows as follow，but looks like it's stuck.
![image](https://user-images.githubusercontent.com/52794487/76729042-38432780-6793-11ea-9cfc-a0f2de9ff01b.png)
In fact, I run the nvidia-smi command from the host to check the GPU usage. It is found that the process that uses the GPU contains the container instance.
![image](https://user-images.githubusercontent.com/52794487/76729185-7d675980-6793-11ea-827c-320f96b7430a.png)

**Comment by adamrehn** [comment] 2020-03-16 06:52
Shipping builds of UE4 projects don't produce much log output, so it's very likely that it's actually running perfectly fine and just not printing any output. At this point you can start the `WebRTCProxy` application and the signalling server and attempt to connect to the UE4 application via a web browser. For this to work correctly, you'll need to either run all three processes in a single container (or a Kubernetes pod), or else run three containers all with `--network=host` so that they can communicate with one another over the loopback address.

**Comment by slnh312** [comment] 2020-03-16 10:23
Adam, I have successfully run the pixel streaming demo in the container. Thank you for your patience and guidance. I have several questions to ask you:
1. Is there any way to control the size of the GPU display memory of a single container instance to prevent resource preemption when multiple container instances run concurrently?
2. The current project does not implement the STUN/TURN function. Is there a migration plan or alternative solution for the STUN/TURN function to meet the public network access requirements?

**Comment by adamrehn** [comment] 2020-03-16 12:43
Awesome, I'm glad you finally managed to get it working nicely. Regarding your questions:

1. The only way of limiting the GPU memory consumption that I'm aware of is by setting the rendering resolution, which will in turn control the framebuffer size. You can set the rendering resolution using command-line flags when running the packaged project (e.g. `-ResX=1920 -ResY=1080`) or by invoking the `setres` command from an [Execute Console Command](https://docs.unrealengine.com/en-US/BlueprintAPI/Development/ExecuteConsoleCommand/index.html) blueprint node in your level blueprint (e.g. `r.setres 1920x1080w`).

2. Take a look at Epic's [Hosting and Networking Guide](https://docs.unrealengine.com/en-US/Platforms/PixelStreaming/Hosting/index.html) for details on using STUN/TURN servers. The Linux versions of the reference servers mentioned on that page are under the `bin` directory in the [WebRTC SDK tarfile for 4.23](https://github.com/adamrehn/pixel-streaming-linux/releases/download/binaries/webrtc-4.23.tar.gz) and are named `stunserver` and `turnserver`.

I'm going to close this issue now that you've got everything working.

**Closed as completed by adamrehn** 2020-03-16 12:43 UTC

**Comment by slnh312** [comment] 2020-03-17 09:12
dear adam，
After entering the container, switch to user root as user ue4. What is the password of user root?
![image](https://user-images.githubusercontent.com/52794487/76841113-4b2d2900-6873-11ea-812d-f7df0eeb2fdc.png)

**Comment by adamrehn** [comment] 2020-03-17 09:41
The root user doesn't have a password set, which is most likely why you're unable to switch to that user using `su`. If you want to run commands with root priveleges then you'll either need to do so using a `RUN` directive in your Dockerfile, or else configure the container image with a root user password or an `/etc/sudoers` file.

Note that general questions regarding the use of the `ue4-runtime` image should be posted as issues on the [ue4-runtime repository](https://github.com/adamrehn/ue4-runtime) rather than this repository, which is only for asking questions about Pixel Streaming for Linux.
